### ISSUE TITLE
Return Search results in a relevant order

### ISSUE THREAD

**Issue by vernastutzman** [sillsdev/webonary#397]
The Search results should be returned in a relevant order by fields.

1) Here is the order for searching for something in the vernacular language; headword in main entry, headword in subentry, headword in minor entry, any cross references, including lexical relations, example sentences, then everything else.

2) Here is the order for searching for something in the analysis languages. Definition, translation of example sentences, notes, then everything else.

**Comment by johntseng** [comment]
Is this request asking for a specific sort order for entries, or would anything that make sense work? It's a lot easier for us to sort by what's visible on the entry: sort by the head word first. If there are multiple head words, sort by the first head word that appears. As a bonus, it's also a lot easier to explain when a user asks "why is it sorted this way"?

This is easier because the data that Flex updates doesn't always look the same. Some have no head word, some have multiple head words, and some have head words that are numerals. We have a field that describes how the data should be displayed, but all the other fields have significant variance. If we want to sort by anything other than how it's displayed, it will require changes on the Flex side, and possibly data clean up.

Is this request also asking for sorting within the entry that's different from how it currently appears? That's going to require some changes on the Flex side and possibly data clean up as well.

**Comment by johntseng** [comment]
After discussing with Han, we'll [Expand Cloud Entry Schema](https://github.com/sillsdev/webonary/issues/404), [Import expanded schema into cloud database](https://github.com/sillsdev/webonary/issues/405), and then [Cloud search should weight fields differently](https://github.com/sillsdev/webonary/issues/406)

**Comment by vernastutzman** [comment]
Comment from Oumar Bah:
Here are my first impressions of the search function: I don't understand how the search results are weighted in the background. In the previous versions, when I searched a word, the headword was the first in the appearance order. Now the order has been inverted. For example, if I search for debbo which means "woman", I will first get another headword, a verb with an example sentence containing debbo, then comes another headword with compounds including debbo and only after that I see the headword debbo itself, that is in the 3d position. Same with junngo "arm & hand". I get first compounds, idioms, a proverb with the catchword. 
There is an improvement: in the previous version headwords with tokens (for example the hyphen after an adjective root) could not be matched unless the user omitted typing the token. One had to type the headword without the token. Now it doesn't matter.

**Comment by stevendyk** [comment]
Closed, Replaced by [#406 Return Search results in a relevant order](https://github.com/sillsdev/webonary/issues/406)

**Comment by vernastutzman** [comment]
We noticed that the relevant order only works when Match whole words is checked:

![image](https://user-images.githubusercontent.com/53490028/213517723-416fde05-70eb-4fc6-b667-38ee2418aaf7.png)
https://www.webonary.work/test-stutzman6?s=paan&search=Search&pos=&semantic_domain=&search_options_set=1&match_whole_words=1&lang=en

It does not work with it unchecked:

<img width="588" alt="image" src="https://user-images.githubusercontent.com/53490028/213518106-bcf5a20f-edd2-46d8-9ad2-6c0a66f8c37c.png">

https://www.webonary.work/test-stutzman6?s=paan&search=Search&pos=&semantic_domain=&search_options_set=1&lang=en
