### ISSUE TITLE
Modify Email that Webonary sends out

### ISSUE THREAD

**Issue by vernastutzman** [sillsdev/webonary#403]
When the Administration Email Address is changed, Webonary sends out the following email:
![image](https://user-images.githubusercontent.com/53490028/188200094-1fac4ca9-4f52-48f1-afe2-76b03ee2841c.png)

Howdy vernastutzman,
Someone with administrator capabilities recently requested to have the administration email address changed on this site:
https://www.webonary.org/lama
To confirm this change, please click on the following link:
https://www.webonary.org/lama/wp-admin/options.php?adminhash=c025f239da0e6573a2ba47d83274007a
You can safely ignore and delete this email if you do not want to take this action.
This email has been sent to [carol_brinneman@wycliffe.org](mailto:carol_brinneman@wycliffe.org)
Regards,
All at Dictionnaire lama
https://www.webonary.org/lama

Let's discuss some wording changes that are more specific and sound more professional.

**Comment by peteroatley** [comment]
It might be helpful to install this plugin to make it easier to edit email templates. I can't tell if it will specifically do this email but it is described as being able to customize WordPress website’s default transactional email designs and templates.

https://wordpress.org/plugins/email-templates/

It should be possible to add the Webonary logo to the email if we wanted.

**Here are my thoughts on changing the wording:**

I'm not sure how to word the salutation since I think it picks up the name of the person who changed the email address which doesn't seem right. It should really be addressed to the site administrator.

Dear \<first\> \<last\>, 
(We could have \"Hello,\" but that is more like spam and it would be nice if we could have a personal greeting)

Someone with administrator capabilities recently requested to have the administration email address changed on this site:
https://www.webonary.org/lama

To confirm this change, please click on the following link:
https://www.webonary.org/lama/wp-admin/options.php?adminhash=c025f239da0e6573a2ba47d83274007a

You can safely ignore and delete this email if you do not want to take this action.

This email has been sent to carol_brinneman@wycliffe.org

Regards,

The Webonary Administration Team

**Comment by phillip-hopper** [comment]
This is the default template,
```
Howdy ###USERNAME###,

Someone with administrator capabilities recently requested to have the
administration email address changed on this site:
###SITEURL###

To confirm this change, please click on the following link:
###ADMIN_URL###

You can safely ignore and delete this email if you do not want to
take this action.

This email has been sent to ###EMAIL###

Regards,
All at ###SITENAME###
###SITEURL###
```

**Comment by phillip-hopper** [comment]
This string is in the file `wordpress/wp-admin/includes/misc.php` which is part of WordPress itself, we cannot change it.
