### ISSUE TITLE
Search Box-Add a filter for Semantic domains

### ISSUE THREAD

**Issue by vernastutzman** [sillsdev/webonary#57]
Add a filter for Semantic domains

**Comment by bbryson** [comment]
Tested this issue.  On the Search page, I used the SemDom dropdown to choose Semantic Domain 3.4
Found several things:

1. The drop-down for searching by SemDoms shows all possible semantic domains.  Should only include the ones that are instantiated in this dictionary.
2. When I don't type anything in the Word box, no results are returned.  It should return all results for the SemDom I chose, if I don't enter any string.
3. When I searched on a SemDom with no results, instead of saying, "no results found", it said, "a critical error has occurred on this site."  It should not say this.
4. When I typed a single letter, it found all words with that SemDom and with that letter in the Headword and also in other fields.  This seems good.
5. When I typed a sequence (abo) it found entries with that SemDom and that substring in the headword and in English definitions.  That seems good.

Here is the URL for the most specific search I did.

https://www.webonary.work/test-stutzman8?s=abo&search=Search&pos=&semantic_domain=3.4&search_options_set=1&lang=en

![SearchSemDom-IncludeAbo-FoundHWandGloss](https://user-images.githubusercontent.com/4039852/213523473-52752ac8-facf-44bf-a440-1215cb8a5084.jpg)
![SearchSemDom-IncludeString-FoundResults](https://user-images.githubusercontent.com/4039852/213523477-515b6fc4-e1d7-4716-8e43-0537e2a417ba.jpg)
![SearchSemDom-NoWord-BeforeSearch](https://user-images.githubusercontent.com/4039852/213523479-e25e761b-a1f7-4ad5-af76-dc8b4d4e0053.jpg)
![SearchSemDom-NoWord-CriticalError](https://user-images.githubusercontent.com/4039852/213523482-b444e11b-3be2-4bf5-8112-d29c4c230539.jpg)

**Comment by stevendyk** [comment]
**1. The drop-down for searching by SemDoms shows all possible semantic domains. Should only include the ones that are instantiated in this dictionary.** 
 _Should this be a separate issue? Is a discrete list of instantiated SemDoms provided by the FLEx upload?_

**2. When I don't type anything in the Word box, no results are returned. It should return all results for the SemDom I chose, if I don't enter any string.**
_I think this needs further evaluation. Perhaps return only an abbreviated list (of headwords?)_

**Comment by stevendyk** [comment]
Verna will review with Beth. There may be additional functionality added to this issue.

**Comment by vernastutzman** [comment]
These items are still not working:
1. When I don't type anything in the Word box, no results are returned. It should return all results for the SemDom I chose, if I don't enter any string.
2. When I searched on a SemDom with no results, instead of saying, "no results found", it said, "a critical error has occurred on this site." It should not say this.

**Comment by phillip-hopper** [comment]
@vernastutzman Webonary cloud will not search for a blank string, so number 1 is not doable at this time.

I have not been able to reproduce number 2. Can you give me exact steps to reproduce it?

**Comment by bbryson** [comment]
On https://www.webonary.work/test-stutzman8
In the SemDom box, choose a domain (e.g., 1.1 Sky)
Leave the "Search" box blank.
Click Search.

Instead of saying "no entries were found", it says, "A critical error has occurred".

(Also happens if I leave the box blank and search for "All Parts of Speech".  But it doesn't happen if I specify a Part of Speech, whether I leave the box blank or no.

**Comment by bbryson** [comment]
Hi, Phil.  I'm not totally clear what you mean when you say "it can't search on a blank string".  I guess I was hoping that something could be done so that when the search box is left blank, then it will search for what would be ".*" in regular expressions.  That is, we don't want to search for a blank string.  We simply don't want to restrict what strings it searches for.  We want it to return all possible strings.  Isn't there something programmatic that can be done to accomplish that?

**Comment by phillip-hopper** [comment]
@bbryson I believe the ability to search with regular expressions has been removed. I haven't been able to do that recently.

**Comment by bbryson** [comment]
Right, and that is good.  My point was:  we're not searching for a blank string.  Isn't there some programmatic way to say, "Don't restrict the strings in any way" or "Search for all possible strings that meet this criterion"?

**Comment by phillip-hopper** [comment]
@bbryson there is currently not a way to do a search with an empty search string. The best alternative I could find is to redirect to the semantic domains page, if one exists.
