### ISSUE TITLE
The `webonary-create-site` plugin is not sending welcome email

### ISSUE THREAD

**Issue by phillip-hopper** [sillsdev/webonary#584]

**Comment by vernastutzman** [comment]
I created a new site on webonary.work with my verna@stutzman.net email, after deleting this user with all the attached sites.
This is what it said:
![image](https://github.com/sillsdev/webonary/assets/53490028/371618ab-c051-43b3-8fc4-ea204a17cc33)

This is the email I received on verna@stutzman.net:
Dear User,

Your new Webonary site has been successfully set up at:
https://www.webonary.work/test-stutzman13/
Your new site comes with a standard set of pages for Front Matter and Back Matter dictionary materials. Please do not remove these pages. The Webonary team can help you provide the necessary information for these pages. It is also important that you do not remove or reorganize the menu items. They have been chosen with great thought.

You can log in to the administrator account with the following information:
Username: verna
Password: 5R8yRNn4WtM7
Log in here: https://www.webonary.work/test-stutzman13/wp-admin

You may access helpful information here: http://www.webonary.work/help/. When you are ready to publish or if you have any questions, please contact us at [webonary@sil.org](mailto:webonary@sil.org).

In order to stay informed about Webonary developments, please sign up for the Dictionary & Lexicography Services newsletter at https://www.webonary.work/join-the-dictionary-lexicography-services-mailing-list/. You may also join the Google User group, https://groups.google.com/g/webonary-list, for interaction with other users.

You are invited to take the Dictionary-Making and Lexicography Course at https://sites.google.com/sil.org/dls-course/.

We hope you enjoy your new site. Thanks!

--The Webonary Team

----------------------------------------------------------------
I was able to log in successfully using the username and password from the email.
